import fs from 'fs';
import path from 'path';
import { isIndexFile, checkIndexFile } from './checkIndexFile';
import { FILETYPE } from '../types';

/** checks for exact match to comment string in index file */
export function checkDir(pathToDir: string, extension: FILETYPE) {
  // parse
  const strArr = fs.readdirSync(pathToDir).filter(p => {
    const stat = fs.statSync(path.join(pathToDir, p));
    return !stat.isDirectory();
  });
  let indexFilePath = null;
  let allFilesExceptIndex: string[] = [];
  strArr.forEach(_x => {
    const x = path.join(pathToDir, _x);
    if (isIndexFile(x)) {
      if (!checkIndexFile(x))
        throw new Error(
          `detected index file that isnt generated by barrelbot: ${x}`
        );
      indexFilePath = x;
    } else {
      if (
        x.split('.').length === 2 && // ignore anything with two dots in the filename eg foo.test.js or bar.stories.js
        x[0] !== '.' // ignore dotfiles
      ) {
        allFilesExceptIndex.push(x);
      }
    }
  });
  const hasIndexFile = !!indexFilePath;
  if (!indexFilePath)
    indexFilePath = path.join(pathToDir, `index.${extension}`);
  return {
    hasIndexFile,
    indexFilePath,
    allFilesExceptIndex
  };
}
