export const COMMENTSTRING =
  '// THIS FILE IS AUTOGENERATED AND MANAGED BY BARRELBOT. DO NOT EDIT';

export type FILETYPE = 'js' | 'jsx' | 'ts' | 'tsx';
export const INDEXFILES = [
  'index.js',
  'index.ts',
  // 'index.jsx',
  'index.jsx',
  'index.tsx'
];
