export const COMMENTSTRING =
  '// THIS FILE IS AUTOGENERATED AND MANAGED BY BARRELBOT. DO NOT EDIT';

export type FILETYPE = 'js' | 'jsx' | 'ts' | 'tsx';
export const INDEXEXTENSIONS = ['js', 'ts', 'jsx', 'tsx'];
export const INDEXFILES = INDEXEXTENSIONS.map(x => 'index.' + x);
